### ISSUE TITLE
`Failed Build Steps` empty

### ISSUE THREAD

**Issue by shmileee** [jdamata/drone-teams#5]
Hi, 

first of all huge kudos for a cool plugin. I've started using it recently with Drone 1.9.0 and unfortunately `Failed Build Steps` always results in an empty card field. My understanding is that it should report exact step that had failed. Perhaps, I'm misusing it in some way, by leveraging multiple pipelines?

`.drone.yml`:
```
---
kind: pipeline
type: kubernetes
name: build
steps:
...

---
kind: pipeline
type: kubernetes
name: notifications
steps:
  - name: notify teams channel
    image: jdamata/drone-teams:latest
    settings:
      webhook:
        from_secret: TEAMS_WEBHOOK
    when:
       status:
         - success
         - failure

trigger:
  ref:
    - refs/heads/master
    - refs/tags/**
  event:
    - push
  status:
    - success
    - failure

depends_on:
  - build
```
